In [1]:
!unzip /content/drive/MyDrive/Alura/Curso_word2vec/cbow_s300.zip

Archive:  /content/drive/MyDrive/Alura/Curso_word2vec/cbow_s300.zip
  inflating: cbow_s300.txt           


In [2]:
import pandas as pd

artigo_treino = pd.read_csv('/content/drive/MyDrive/Alura/Curso_word2vec/treino.csv')
artigo_teste = pd.read_csv('/content/drive/MyDrive/Alura/Curso_word2vec/teste.csv')
artigo_treino.head(10)

title  ...                                               link
0  Após polêmica, Marine Le Pen diz que abomina n...  ...  http://www1.folha.uol.com.br/mundo/2017/04/187...
1  Macron e Le Pen vão ao 2º turno na França, em ...  ...  http://www1.folha.uol.com.br/mundo/2017/04/187...
2  Apesar de larga vitória nas legislativas, Macr...  ...  http://www1.folha.uol.com.br/mundo/2017/06/189...
3  Governo antecipa balanço, e Alckmin anuncia qu...  ...  http://www1.folha.uol.com.br/cotidiano/2015/07...
4  Após queda em maio, a atividade econômica sobe...  ...  http://www1.folha.uol.com.br/mercado/2017/08/1...
5  Barcelona vence de virada; Atlético de Madri b...  ...  http://www1.folha.uol.com.br/esporte/2016/09/1...
6  'Spartacus' oferece um duplo retrato de batalh...  ...  http://www1.folha.uol.com.br/ilustrada/2016/12...
7  Sobe para 86 o número de mortos no atentado te...  ...  http://www1.folha.uol.com.br/mundo/2016/08/180...
8  Premiada em Sundance, Crystal Moselle retrata ...  ...  http://www1.folha.uol.com.br/ilustrada/2016/09...
9  Metroviários e ferroviários ameaçam parar na p...  ...  http://www1.folha.uol.com.br/cotidiano/2017/07...

[10 rows x 6 columns]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

texto = [
         "tenha um bom dia",
         "tenha um péssimo dia",
         "tenha um ótimo dia"
]

vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [4]:
vetorizador.vocabulary_

{'bom': 0, 'dia': 1, 'péssimo': 2, 'tenha': 3, 'um': 4, 'ótimo': 5}

In [5]:
vetor_bom = vetorizador.transform(['bom'])
print((vetor_bom.toarray()))

[[1 0 0 0 0 0]]


In [6]:
vetor_exemplo = vetorizador.transform(["tenha um ótimo dia"])
print(vetor_exemplo.toarray())

[[0 1 0 1 1 1]]


In [7]:
from gensim.models import KeyedVectors

In [8]:
modelo = KeyedVectors.load_word2vec_format("cbow_s300.txt")

In [9]:
modelo.most_similar("brasil") # vetores próximos ao vetor da palavra brasil

[('japão', 0.7412911653518677),
 ('brasil.', 0.6550555229187012),
 ('pradã£o', 0.6525028347969055),
 ('haiti', 0.648073673248291),
 ('ocidente', 0.6387284994125366),
 ('trapichão', 0.6379075050354004),
 ('romildão', 0.6373966932296753),
 ('emtanto', 0.6351075172424316),
 ('romildã£o', 0.6259243488311768),
 ('beira-rio.', 0.6231665015220642)]

In [10]:
modelo.most_similar(positive=['brasil', 'argentina']) # vetores próximos ao vetor da soma "brasil + argentina"

[('chile', 0.6781662702560425),
 ('peru', 0.6348033547401428),
 ('venezuela', 0.6273865103721619),
 ('equador', 0.6037014722824097),
 ('bolívia', 0.6017140746116638),
 ('haiti', 0.5993807315826416),
 ('méxico', 0.5962306261062622),
 ('paraguai', 0.5957703590393066),
 ('uruguai', 0.5903672575950623),
 ('japão', 0.5893509984016418)]

In [11]:
modelo.most_similar(positive=['brasil', 'argentina'], negative=['peru']) # vetores próximos do vetor "brasil + argentina - peru"

[('austrália', 0.4520353674888611),
 ('europa', 0.4477105438709259),
 ('suíça', 0.42705434560775757),
 ('semifinal.', 0.4250774383544922),
 ('itália', 0.421775221824646),
 ('dfb-pokal', 0.4197959303855896),
 ('iacúitia', 0.4184972047805786),
 ('chipmusic', 0.4183228015899658),
 ('china', 0.41520628333091736),
 ('rússia', 0.41390737891197205)]

In [12]:
modelo.most_similar(positive=['nuvens', 'estrela'], negative=['nuvem']) # nuvens + estrela - nuvem = estrelas

[('estrelas', 0.5497429966926575),
 ('plêiades', 0.379197895526886),
 ('colinas', 0.3746805191040039),
 ('trovoadas', 0.373703271150589),
 ('sombras', 0.3734194040298462),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727698802948),
 ('cigarras', 0.36065393686294556),
 ('galáxias', 0.35754913091659546),
 ('luas', 0.3575345277786255)]

In [13]:
modelo.most_similar(positive=['mulher','professor'], negative=['homem']) # mulher + professor - homem = professora

[('professora', 0.6192208528518677),
 ('aluna', 0.5449554324150085),
 ('esposa', 0.4978231191635132),
 ('ex-aluna', 0.4884248375892639),
 ('namorada', 0.4737858772277832),
 ('enfermeira', 0.4728144109249115),
 ('filha', 0.467373788356781),
 ('irmã', 0.45845913887023926),
 ('ex-namorada', 0.45824766159057617),
 ('ex-professora', 0.4510470926761627)]

In [14]:
artigo_treino.title.loc[1]

'Macron e Le Pen vão ao 2º turno na França, em revés de siglas tradicionais'

In [15]:
import string
import nltk
nltk.download('punkt')

def tokenizador(texto):
  texto = texto.lower() # deixa o texto minusculo
  lista_alfanumerico = [] 

  for token_valido in nltk.word_tokenize(texto): # para cada elemento do texto
    if token_valido in string.punctuation: continue # se o elemento for pontuação, ignora
    lista_alfanumerico.append(token_valido) # se for palavra, salva na lista

  return lista_alfanumerico

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [16]:
palavras_teste = tokenizador("Hoje é um novo dia, de um novo tempo, que começou")
print(palavras_teste)

['hoje', 'é', 'um', 'novo', 'dia', 'de', 'um', 'novo', 'tempo', 'que', 'começou']


In [17]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [18]:
# criando a função para tornar as frases em vetores 

import numpy as np
def combinacao_de_vetores_por_soma(palavras_numeros):
  vetor_resultante = np.zeros(300) # tamanho do modelo já treinado
  for pn in palavras_numeros:
    try: 
      vetor_resultante += modelo.get_vector(pn)
    except KeyError:
      if pn.isnumeric(): # segundo o artigo do nilc, todo os numeros devem ser convertidos para zeros
        pn = "0"*len(pn)
        vetor_resultante += modelo.get_vector(pn)
      else:
        vetor_resultante += modelo.get_vector('unknown') # também segundo o artigo, todas as palavras desconhecidas devem ser convertidas para 'unknown'
    
  return vetor_resultante

In [19]:
palavras_numeros = tokenizador('Hoje, dia 14 do 16 onde o sol torce a meia noite na cidade de Vakulkex')
vetor_texto = combinacao_de_vetores_por_soma(palavras_numeros)
len(vetor_texto)

300

In [20]:
# agora, fazer a vetorização de todos os títulos do texto
def matriz_vetores(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x,y))

  for i in range(x):
    palavras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_de_vetores_por_soma(palavras_numeros)

  return matriz

In [21]:
matriz_vetores_treino = matriz_vetores(artigo_treino.title)
matriz_vetores_teste = matriz_vetores(artigo_teste.title)
print(matriz_vetores_treino.shape)
print(matriz_vetores_teste.shape)

(90000, 300)
(20513, 300)


In [22]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(max_iter=200)

LR.fit(matriz_vetores_treino, artigo_treino.category)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
LR.n_iter_ # quantas iterações foram necessárias para convergir

array([127], dtype=int32)

In [24]:
LR.score(matriz_vetores_teste, artigo_teste.category)

0.7964705308828548

In [25]:
artigo_teste.category.unique() # Quais categorias temos 

array(['colunas', 'esporte', 'mercado', 'cotidiano', 'mundo', 'ilustrada'],
      dtype=object)

In [26]:
from sklearn.metrics import classification_report

label_prevista = LR.predict(matriz_vetores_teste)
CR = classification_report(artigo_teste.category, label_prevista)
print(CR)

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.93      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [ ]:
# 0.86 de precisão significa que apenas 86% do que estou classificando como coluna é de fato coluna 
# 0.72 de recall significa que o que classifiquei como coluna representa apenas 72% do que é coluna de fato. 
# macro avg é a média comum dos valores
# weighted avg é a média ponderada dos valores, onde os pesos são as quantidades de dados

In [31]:
# Realizar uma comparação com o DummyClassifier

from sklearn.dummy import DummyClassifier

DC = DummyClassifier()
DC.fit(matriz_vetores_treino, artigo_treino.category)
label_prevista_dc = DC.predict(matriz_vetores_teste)

/usr/local/lib/python3.7/dist-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)


In [32]:
CR_dummy = classification_report(label_prevista_dc, artigo_teste.category)
print(CR_dummy)

              precision    recall  f1-score   support

     colunas       0.17      0.29      0.21      3439
   cotidiano       0.17      0.08      0.11      3420
     esporte       0.16      0.22      0.19      3436
   ilustrada       0.20      0.01      0.01      3386
     mercado       0.17      0.30      0.22      3399
       mundo       0.18      0.11      0.14      3433

    accuracy                           0.17     20513
   macro avg       0.17      0.17      0.15     20513
weighted avg       0.17      0.17      0.15     20513



## Utilizando agora SkipGram ao invez de CBOW

In [37]:
# Descompactando o SkipGram300
!unzip "/content/drive/MyDrive/Alura/Curso_word2vec/skip_s300.zip"
modelo_skipgram = KeyedVectors.load_word2vec_format("skip_s300.txt")

Archive:  /content/drive/MyDrive/Alura/Curso_word2vec/skip_s300.zip
  inflating: skip_s300.txt           


In [41]:
def combinacao_de_vetores_por_soma_skipgram(palavras_numeros):
  vetor_resultante = np.zeros(300)
  for pn in palavras_numeros:
    try: 
      vetor_resultante += modelo_skipgram.get_vector(np)

    except KeyError:
      if pn.isnumeric():
        pn = "0"*len(pn)
        vetor_resultante += modelo_skipgram.get_vector(pn)
      else:
        vetor_resultante += modelo_skipgram.get_vector("unknown")

  return vetor_resultante

In [42]:
def matriz_vetores_skipgram(textos):
  x = len(textos)
  y = 300
  matriz = np.zeros((x,y))

  for i in range(x):
    palabras_numeros = tokenizador(textos.iloc[i])
    matriz[i] = combinacao_de_vetores_por_soma_skipgram(palavras_numeros)

  return matriz

In [43]:
matriz_vetores_treino_skipgram = matriz_vetores_skipgram(artigo_treino.title)
matriz_vetores_teste_skipgram = matriz_vetores_skipgram(artigo_teste.title)

In [44]:
LR_skipgram = LogisticRegression(max_iter=1000)
LR_skipgram.fit(matriz_vetores_treino_skipgram, artigo_treino.category)
label_previsao_skipgram = LR_skipgram.predict(matriz_vetores_teste)

CR_skipgram = classification_report(artigo_teste.category, label_previsao_skipgram)
print(CR_skipgram)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

     colunas       0.30      1.00      0.46      6103
   cotidiano       0.00      0.00      0.00      1698
     esporte       0.00      0.00      0.00      4663
   ilustrada       0.00      0.00      0.00       131
     mercado       0.00      0.00      0.00      5867
       mundo       0.00      0.00      0.00      2051

    accuracy                           0.30     20513
   macro avg       0.05      0.17      0.08     20513
weighted avg       0.09      0.30      0.14     20513



In [70]:
modelo.most_similar("marlon")

[('franjic', 0.5553466081619263),
 ('zettel', 0.5153762102127075),
 ('saidenberg', 0.5150594711303711),
 ('wrigg', 0.4965270161628723),
 ('roni', 0.48893144726753235),
 ('lendl', 0.4878675639629364),
 ('sotto', 0.48757821321487427),
 ('dodig', 0.48716670274734497),
 ('gralak', 0.47468793392181396),
 ('rakitic', 0.4681442379951477)]

In [69]:
modelo.vocab

{'</s>': <gensim.models.keyedvectors.Vocab at 0x7fa91d703790>,
 ',': <gensim.models.keyedvectors.Vocab at 0x7fa91dbcc250>,
 'de': <gensim.models.keyedvectors.Vocab at 0x7fa91d7037d0>,
 '.': <gensim.models.keyedvectors.Vocab at 0x7fa91fea7d10>,
 'a': <gensim.models.keyedvectors.Vocab at 0x7fa91d703810>,
 'o': <gensim.models.keyedvectors.Vocab at 0x7fa91fea7f90>,
 'e': <gensim.models.keyedvectors.Vocab at 0x7fa91d703890>,
 'que': <gensim.models.keyedvectors.Vocab at 0x7fa91fea7a90>,
 'do': <gensim.models.keyedvectors.Vocab at 0x7fa91d703910>,
 'da': <gensim.models.keyedvectors.Vocab at 0x7fa91fea7c90>,
 'em': <gensim.models.keyedvectors.Vocab at 0x7fa91d703950>,
 'para': <gensim.models.keyedvectors.Vocab at 0x7fa91d6f1b50>,
 'um': <gensim.models.keyedvectors.Vocab at 0x7fa91d7039d0>,
 'no': <gensim.models.keyedvectors.Vocab at 0x7fa91d6f1c50>,
 'com': <gensim.models.keyedvectors.Vocab at 0x7fa91d703a50>,
 'é': <gensim.models.keyedvectors.Vocab at 0x7fa91d6f9290>,
 'uma': <gensim.models.k